// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Fee fee
//
// swagger:model Fee
type Fee struct {

	// t
	T int64 `json:"t,omitempty"`

	// v
	V float64 `json:"v,omitempty"`
}

// Validate validates this fee
func (m *Fee) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this fee based on context it is used
func (m *Fee) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Fee) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Fee) UnmarshalBinary(b []byte) error {
	var res Fee
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
