// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GLND API Swagger",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/fees": {
      "get": {
        "tags": [
          "Fees"
        ],
        "operationId": "Fees",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Fees"
            }
          },
          "404": {
            "description": "data not found",
            "schema": {
              "$ref": "#/definitions/ApiInvalidResponse"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/ApiInvalidResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiInvalidResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Fee": {
      "type": "object",
      "properties": {
        "t": {
          "type": "integer",
          "format": "int64"
        },
        "v": {
          "type": "number",
          "format": "double"
        }
      }
    },
    "Fees": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Fee"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GLND API Swagger",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/fees": {
      "get": {
        "tags": [
          "Fees"
        ],
        "operationId": "Fees",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Fees"
            }
          },
          "404": {
            "description": "data not found",
            "schema": {
              "$ref": "#/definitions/ApiInvalidResponse"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/ApiInvalidResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiInvalidResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Fee": {
      "type": "object",
      "properties": {
        "t": {
          "type": "integer",
          "format": "int64"
        },
        "v": {
          "type": "number",
          "format": "double"
        }
      }
    },
    "Fees": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Fee"
      }
    }
  }
}`))
}
