// Code generated by go-swagger; DO NOT EDIT.

package fees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kshamko/glnd/internal/models"
)

// FeesOKCode is the HTTP code returned for type FeesOK
const FeesOKCode int = 200

/*FeesOK A successful response.

swagger:response feesOK
*/
type FeesOK struct {

	/*
	  In: Body
	*/
	Payload models.Fees `json:"body,omitempty"`
}

// NewFeesOK creates FeesOK with default headers values
func NewFeesOK() *FeesOK {

	return &FeesOK{}
}

// WithPayload adds the payload to the fees o k response
func (o *FeesOK) WithPayload(payload models.Fees) *FeesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fees o k response
func (o *FeesOK) SetPayload(payload models.Fees) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FeesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Fees{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// FeesNotFoundCode is the HTTP code returned for type FeesNotFound
const FeesNotFoundCode int = 404

/*FeesNotFound data not found

swagger:response feesNotFound
*/
type FeesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIInvalidResponse `json:"body,omitempty"`
}

// NewFeesNotFound creates FeesNotFound with default headers values
func NewFeesNotFound() *FeesNotFound {

	return &FeesNotFound{}
}

// WithPayload adds the payload to the fees not found response
func (o *FeesNotFound) WithPayload(payload *models.APIInvalidResponse) *FeesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fees not found response
func (o *FeesNotFound) SetPayload(payload *models.APIInvalidResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FeesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FeesInternalServerErrorCode is the HTTP code returned for type FeesInternalServerError
const FeesInternalServerErrorCode int = 500

/*FeesInternalServerError Error response

swagger:response feesInternalServerError
*/
type FeesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIInvalidResponse `json:"body,omitempty"`
}

// NewFeesInternalServerError creates FeesInternalServerError with default headers values
func NewFeesInternalServerError() *FeesInternalServerError {

	return &FeesInternalServerError{}
}

// WithPayload adds the payload to the fees internal server error response
func (o *FeesInternalServerError) WithPayload(payload *models.APIInvalidResponse) *FeesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fees internal server error response
func (o *FeesInternalServerError) SetPayload(payload *models.APIInvalidResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FeesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
