// Code generated by go-swagger; DO NOT EDIT.

package fees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FeesHandlerFunc turns a function with the right signature into a fees handler
type FeesHandlerFunc func(FeesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FeesHandlerFunc) Handle(params FeesParams) middleware.Responder {
	return fn(params)
}

// FeesHandler interface for that can handle valid fees params
type FeesHandler interface {
	Handle(FeesParams) middleware.Responder
}

// NewFees creates a new http.Handler for the fees operation
func NewFees(ctx *middleware.Context, handler FeesHandler) *Fees {
	return &Fees{Context: ctx, Handler: handler}
}

/* Fees swagger:route GET /fees Fees fees

Fees fees API

*/
type Fees struct {
	Context *middleware.Context
	Handler FeesHandler
}

func (o *Fees) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFeesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
